services:
    health_check:
      public: true
      class: App\Controller\HealthCheckController
      arguments:
        - '%build_revision%'

    auth_controller:
      public: true
      class: App\Authentication\AuthController
      arguments:
        $userProvider: '@user_provider'
        $authService: '@auth_service'
        $passwordService: '@password_service'

    task_controller:
      public: true
      class: App\Task\TaskController
      arguments:
        $taskProvider: '@task_provider'
        $userProvider: '@user_provider'

    user_controller:
      public: true
      class: App\User\UserController
      arguments:
        $userProvider: '@user_provider'

