health-check:
  path: /health-check
  controller: health_check:healthCheck

signin:
  path: /signin
  methods: [POST]
  controller: auth_controller:signIn

signup:
  path: /signup
  methods: [POST]
  controller: auth_controller:signUp

task_add:
  path: /task-add
  methods: [POST]
  controller: task_controller:addTask

task_update:
  path: /task-update
  methods: [POST]
  controller: task_controller:updateTask

task_delete:
  path: /task-delete
  methods: [POST]
  controller: task_controller:deleteTask

task_list:
  path: /task-list
  methods: [GET]
  controller: task_controller:listTasks

users_list:
  path: /users-list
  methods: [GET]
  controller: user_controller:listUsers

user_update:
  path: /user-update
  methods: [POST]
  controller: user_controller:updateUser
