health-check:
  path: /health-check
  controller: health_check:healthCheck

signin:
  path: /signin
  methods: [POST]
  controller: auth_controller:signIn

register:
  path: /register
  methods: [POST]
  controller: auth_controller:register
