imports:
    - { resource: controllers.yaml }

parameters:
  db_config:
    connections:
      - { name: master, dsn: '%env(DB_CONNECTION)%' }

services:
    App\Exception\DefaultExceptionHandler:
        arguments:
            $isDebug: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\Response\JsonDataResponseHandler:
        tags:
            - { name: kernel.event_listener, event: kernel.view }
    App\Authentication\AuthenticationListener:
        arguments:
            - '@auth_service'
        tags:
            - { name: kernel.event_listener, event: kernel.controller }

    auth_service:
        class: App\Authentication\SimpleAuthService

    user_provider:
        class: App\User\SqlUserProvider
        arguments:
          $connection: '@master_connection'

    password_service:
        class: App\Authentication\PasswordService
        arguments:
            $salt: '%env(APP_SECRET)%'

    task_provider:
        class: App\Task\SqlTaskProvider
        arguments:
          $connection: '@master_connection'

