imports:
    - { resource: controllers.yaml }

parameters:

services:
    App\Exception\DefaultExceptionHandler:
        arguments:
            $isDebug: true
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    App\Response\JsonDataResponseHandler:
        tags:
            - { name: kernel.event_listener, event: kernel.view }

